### ISSUE TITLE
[BUG] User can scroll in all webpages and see white space

### ISSUE THREAD

**Issue by DoodlePooge** [obscuritylabs/darkmoon#110]
We should not be able to scroll our entire webpage layout, the scrollable section should be a container or box that has our set background.

**Comment by siric-4321** [comment]
We tried scrolling up and down and we don't see any white spaces.

**Comment by tclasen** [comment]
I am unable to replicate this problem on any commit on trunk within the past 4 days. Closing ticket without reproducible evidence of a bug. Feel free to reopen with pictures, video, or clear DOM elements of concern.
