### ISSUE TITLE
Throw an Exception for the case that there is missing input (i.e. missing hashes)

### ISSUE THREAD

**Issue by DoodlePooge** [obscuritylabs/darkmoon#56]
Currently an error with our POST endpoint we don't handle the case where the API does not receive all the data the schema is checking for like the hashes. We should be handling this issue with likely a 422 response code.

Link: https://github.com/obscuritylabs/darkmoon/pull/71

**Comment by asmitakarandikar** [comment]
Looked over the PR for this ticket and everything looks good!
